# Generated by Django 2.2.4 on 2019-10-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20191001_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktop',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='laptop',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='Price',
            new_name='price',
        ),
    ]
